name: seller_side_uo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  image_picker: ^1.0.7
  flutter:
    sdk: flutter
  dio: ^4.0.0
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^2.0.0
    
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_fonts: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  
